mod TEST is
	pr CMD .

	ops eg0 eg1 eg2 eg3 : -> LearnCourse .
	eq eg0 =
		course on "TEST"
			teaches < 'A >, < 'B > and < 'C >
		with
			teaching strategy < 's >
				< 'B > before < 'C >
		learning object < 'A > has title "TEST A"
		learning object < 'B > has title "TEST B"
		learning object < 'C > has title "TEST C"
	.
	eq eg1 =
		course on "Linguagens Formais"
			teaches < 'int3 >, < 'sec3_2 >, < 'sec3_1 >, < 'fig3_2 >, < 'ex3_1 > and < 'ex3_2 >
		learning object < 'int3 > has
			title "Introducao ao Capitulo 3"
			image "auto.png"
			text "O estudo das linguagens regulares..."
		learning object < 'sec3_2 > has
			title "Secao 3.2"
			text "A construcao de um sistema e, em geral..."
		learning object < 'sec3_1 > has
			title "Secao 3.1"
			text "Um sistema de estados finitos e um modelo matematico..."
		learning object < 'fig3_2 > has
			title "Figura 3.2"
			image "figura3.2.png"
			text "Diagrama (AFD): transicao"
		learning object < 'ex3_1 > has
			title "Exercicio 3.1"
			text "Sobre as linguagens regulares:..."
		learning object < 'ex3_2 > has
			title "Exercicio 3.2"
			text "Desenvolva automatos finitos deterministicos..."
	.
	eq eg2 =
		course on "Linguagens Formais"
			teaches < 'sec2_1 >, < 'sec2_2 >, < 'sec2_4 >, < 'int3 >, < 'sec3_1 >, < 'sec3_2 >, < 'sec3_3 >, < 'fig3_2 >, < 'sec3_7 >, < 'ex3_1 > and < 'ex3_2 >
		with
			teaching strategy < 'class >
				< 'int3 > before < 'sec3_1 >,
				< 'sec3_1 > before < 'sec3_2 >,
				< 'sec3_2 > before < 'fig3_2 >,
				< 'fig3_2 > before < 'sec2_1 >,
				< 'sec2_1 > before < 'sec2_2 >,
				< 'sec2_2 > before < 'sec3_3 >,
				< 'sec3_3 > before < 'sec2_4 >,
				< 'sec2_4 > before < 'sec3_7 >,
				< 'sec3_7 > before < 'ex3_1 >,
				< 'ex3_1 > before < 'ex3_2 >
			teaching strategy < 'book >
				< 'sec2_1 > before < 'sec2_2 >,
				< 'sec2_2 > before < 'sec2_4 >,
				< 'sec2_4 > before < 'int3 >,
				< 'int3 > before < 'sec3_1 >,
				< 'sec3_1 > before < 'sec3_2 >,
				< 'sec3_2 > before < 'sec3_3 >,
				< 'sec3_3 > before < 'fig3_2 >,
				< 'fig3_2 > before < 'sec3_7 >,
				< 'sec3_7 > before < 'ex3_1 >,
				< 'ex3_1 > before < 'ex3_2 >
		learning object < 'int3 > has
			title "Introducao ao Capitulo 3"
			image "auto.png"
			text "O estudo das linguagens regulares..."
		learning object < 'sec2_1 > has
			title "Secao 2.1"
			text "alfabeto"
		learning object < 'sec2_2 > has
			title "Secao 2.2"
			text "palavra"
		learning object < 'sec2_4 > has
			title "Secao 2.4"
			text "gramatica"
		learning object < 'sec3_1 > has
			title "Secao 3.1"
			text "Um sistema de estados finitos e um modelo matematico..."
		learning object < 'sec3_2 > has
			title "Secao 3.2"
			text "A construcao de um sistema e, em geral..."
		learning object < 'sec3_3 > has
			title "Secao 3.3"
			text "automato finito..."
		learning object < 'sec3_7 > has
			title "Secao 3.7"
			text "gramatica regular..."
		learning object < 'fig3_2 > has
			title "Figura 3.2"
			image "figura3.2.png"
			text "Diagrama (AFD): transicao"
		learning object < 'ex3_1 > has
			title "Exercicio 3.1"
			text "Sobre as linguagens regulares:..."
		learning object < 'ex3_2 > has
			title "Exercicio 3.2"
			text "Desenvolva automatos finitos deterministicos..."
	.
	eq eg3 =
		course on "Linguagens Formais"
			teaches < 'int3 >, < 'sec3_2 >, < 'sec3_1 >, < 'fig3_2 >, < 'ex3_1 > and < 'ex3_2 >
		with
			exercises < 'ex3_1 > and < 'ex3_2 >
			teaching strategy < 'ex >
				exercises after all but the exercises
		learning object < 'int3 > has
			title "Introducao ao Capitulo 3"
			image "auto.png"
			text "O estudo das linguagens regulares..."
		learning object < 'sec3_2 > has
			title "Secao 3.2"
			text "A construcao de um sistema e, em geral..."
		learning object < 'sec3_1 > has
			title "Secao 3.1"
			text "Um sistema de estados finitos e um modelo matematico..."
		learning object < 'fig3_2 > has
			title "Figura 3.2"
			image "figura3.2.png"
			text "Diagrama (AFD): transicao"
		learning object < 'ex3_1 > has
			title "Exercicio 3.1"
			text "Sobre as linguagens regulares:..."
		learning object < 'ex3_2 > has
			title "Exercicio 3.2"
			text "Desenvolva automatos finitos deterministicos..."
	.
endm